### ISSUE TITLE
Controllers

### ISSUE THREAD

**Issue by valter-junior** [valter-junior/todolist#9]
# Description
Controllers are the holders of the application business rules. They should treat most expected exceptions (the ones that are unexpected should be treated in routes). Some times they can be complex, gluing together multiple models, and external services, other times they can be very simple, only doing simple query in database.

# References
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes

# Tasks
- [x] login
- [ ] register
- [x] list todo lists
- [x] create todo list
- [x] delete todo list
- [x] create task
- [ ] mask/unmark task
- [x] delete task
